// Auto-generated by genabi.mjs
// Do not edit manually

export const BambooHoldSpeechAddresses = {
  "localhost": "0x16181f40241a3fD0775c8826eB5fC1e9991e42e7",
  "sepolia": "0xaE0deEa611083EBF747Dd9f2b6047d654EBD1C14"
} as const;

export type NetworkAddresses = {
  [network: string]: string;
};

export function getBambooHoldSpeechAddress(chainId: number): string | undefined {
  const chainIdToNetwork: { [key: number]: string } = {
    31337: "localhost",
    11155111: "sepolia",
  };

  const network = chainIdToNetwork[chainId];
  return network ? BambooHoldSpeechAddresses[network as keyof typeof BambooHoldSpeechAddresses] : undefined;
}
