#!/usr/bin/env node

/**
 * Generate ABI files from Hardhat deployments
 * Reads from ../fhevm-hardhat-template/deployments and generates TypeScript files
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const FRONTEND_ROOT = join(__dirname, "..");
const HARDHAT_ROOT = join(FRONTEND_ROOT, "..", "fhevm-hardhat-template");
const ABI_OUTPUT_DIR = join(FRONTEND_ROOT, "abi");

// Ensure output directory exists
if (!existsSync(ABI_OUTPUT_DIR)) {
  mkdirSync(ABI_OUTPUT_DIR, { recursive: true });
}

/**
 * Generate ABI and address files for a contract
 */
function generateContractFiles(contractName, networks = ["localhost", "sepolia"]) {
  console.log(`\nGenerating ABI for ${contractName}...`);

  const addresses = {};
  let abi = null;

  // Try to read from each network deployment
  for (const network of networks) {
    const deploymentPath = join(
      HARDHAT_ROOT,
      "deployments",
      network,
      `${contractName}.json`
    );

    if (existsSync(deploymentPath)) {
      try {
        const deployment = JSON.parse(readFileSync(deploymentPath, "utf-8"));
        addresses[network] = deployment.address;

        // Use first available ABI
        if (!abi && deployment.abi) {
          abi = deployment.abi;
        }

        console.log(`  ✓ Found ${network} deployment at ${deployment.address}`);
      } catch (error) {
        console.warn(`  ⚠ Error reading ${network} deployment:`, error.message);
      }
    }
  }

  if (!abi) {
    console.error(`  ✗ No ABI found for ${contractName}`);
    return false;
  }

  // Generate ABI TypeScript file
  const abiContent = `// Auto-generated by genabi.mjs
// Do not edit manually

export const ${contractName}ABI = ${JSON.stringify(abi, null, 2)} as const;

export type ${contractName}ABI = typeof ${contractName}ABI;
`;

  writeFileSync(join(ABI_OUTPUT_DIR, `${contractName}ABI.ts`), abiContent);
  console.log(`  ✓ Generated ${contractName}ABI.ts`);

  // Generate addresses TypeScript file
  const addressesContent = `// Auto-generated by genabi.mjs
// Do not edit manually

export const ${contractName}Addresses = ${JSON.stringify(addresses, null, 2)} as const;

export type NetworkAddresses = {
  [network: string]: string;
};

export function get${contractName}Address(chainId: number): string | undefined {
  const chainIdToNetwork: { [key: number]: string } = {
    31337: "localhost",
    11155111: "sepolia",
  };

  const network = chainIdToNetwork[chainId];
  return network ? ${contractName}Addresses[network as keyof typeof ${contractName}Addresses] : undefined;
}
`;

  writeFileSync(
    join(ABI_OUTPUT_DIR, `${contractName}Addresses.ts`),
    addressesContent
  );
  console.log(`  ✓ Generated ${contractName}Addresses.ts`);

  return true;
}

// Main execution
console.log("=== ABI Generation Script ===");
console.log(`Hardhat root: ${HARDHAT_ROOT}`);
console.log(`Output directory: ${ABI_OUTPUT_DIR}`);

// Check if Hardhat root exists (for local development)
const hardhatExists = existsSync(HARDHAT_ROOT);
const abiFileExists = existsSync(join(ABI_OUTPUT_DIR, "BambooHoldSpeechABI.ts"));

if (!hardhatExists) {
  // In Vercel/build environment, Hardhat project may not be available
  // Check if ABI files already exist (committed to git)
  if (abiFileExists) {
    console.log("⚠ Hardhat project not found, but ABI files exist. Skipping generation.");
    console.log("✓ Using existing ABI files");
    process.exit(0);
  } else {
    console.error("✗ Hardhat project not found and ABI files don't exist");
    console.error("  Please ensure ABI files are committed to git or Hardhat project is available");
    process.exit(1);
  }
}

const success = generateContractFiles("BambooHoldSpeech");

if (success) {
  console.log("\n✓ ABI generation completed successfully");
} else {
  console.error("\n✗ ABI generation failed");
  process.exit(1);
}

